### PR TITLE
website design overhaul; closes #13; closes #14

### LINKED ISSUE #13: create links for subsections
it was nice to send a link to someone to a specific subsection in the troubleshooting wiki and there is not way to do that now.  can we setup a table of contents or some kind of section hyperlink to bring this back?

### LINKED ISSUE #14: add link for survey page to navbar under "more"

### PR DESCRIPTION
**Pull request by cole-brokamp**

### CODE REVIEW

**Comment by andrew-vancil** [comment]
Here's the updates that I've made:
- Reformatted pages to use the floating table of contents
    - Reworked headers
 - Added command line information
 - Added sample workflow from paper under Cohort Guides. 
     - Do we want to keep it there or move it under Using DeG?
 - Added hex logo to navbar
 - Updated wording/titles here and there

Is there a good way to put the site together and test it? I didn't want to mess up anything with the current site

**Comment by cole-brokamp** [comment]
I will check it out locally and build the site, thanks!

**Comment by andrew-vancil** [comment]
I made a few more updates based on our discussion yesterday. 

I'm having trouble putting a custom image in place of the home icon from FontAwesome. FA has a map marker icon that I put there for now, but there's gotta be a way to edit the html blurb at the bottom of the header.html file. I've been playing around with it without success so far, but I'll circle back and see if I can get it figured.

**Comment by cole-brokamp** [comment]
cool, I will take a look (for real this time!)

**Comment by cole-brokamp** [comment]
I did a lot of content editing and changing of the titles for a cleaner layout, especially in the floating TOCs.  Pull this down and build it locally to look over anything I might have missed or been mistaken on.  After this, I'd like to get @erikarasnick's review before we make it live.

**Comment by andrew-vancil** [comment]
It seems solid to me! The troubleshooting page is definitely a lot less cluttered with headers, but the important information looks to be there.

**Comment by erikarasnick** [comment]
@andrew-vancil can you update the lockfile to include all packages needed to build the site (bslib, etc)? Long story, but I'm having problems installing packages at the moment... related to updating my OS 🙃 . I already have bslib installed globally, but I can't get it installed in this project.

**Comment by andrew-vancil** [comment]
Hmm, looks like when I went to update the lockfile and push it up, it is saying that its already up to date. Last week when I first came back to this, I had a heck of a time getting my projects to update, too. I ended up having to update R itself and then restore the renv.

Was this your error? "Error: Providing a list to `theme` requires the bslib package.Execution haltedError: Failed to run 'function(...) {' in a new R session.Execution halted " ?

**Comment by cole-brokamp** [comment]
bslib is not included explicitly in renv, but I think it is suggested.  i just added a dummy file so that it would be picked up.  try with this updated renv.lock file now

**Comment by erikarasnick** [comment]
that worked in terms of including it in the lock file, but then renv tries to update the bslib and sass which leads me to the same error. 

This is the error
```
Error in if (eval(cond, envir = environment(dot))) return(eval(expr, envir = environment(dot))) : 
  the condition has length > 1
In addition: Warning message:
In system2(R(), args, stdout = TRUE, stderr = TRUE) :
  running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD config CC 2>&1' had status 72
```

but it brings up the prompt about command line developer tools and make, which is the same issue I was having with git before I manually installed it. I manually installed make and used the alias for gmake/make but apparently it's not picking it up. Sorry this convo probably shouldn't be on this thread...

**Comment by cole-brokamp** [comment]
hmmm.  i'll go ahead and merge for now.  have you tried installing xcode developer tools from scratch?

**Comment by erikarasnick** [comment]
Finally got everything working on my end. I don't have any edits. Looks good... more user-friendly and easier to follow!

**Pull request merged**
