### PR TITLE
move all content from wiki

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by erikarasnick** [comment]
@cole-brokamp I think I've made all the changes we discussed so far.

**Comment by erikarasnick** [comment]
I added the schwartz guide... I have the PEPR guide ready to add, but wasn't sure if I should because it includes an example of the crime data. Would "publishing" 3 lines of the crime data go against our agreement with AGS?

**Comment by cole-brokamp** [comment]
I think adding the example crime data will be okay to publish.

**Review by cole-brokamp — APPROVED** [review]

**Comment by cole-brokamp** [comment]
favicons are working when it is live!!  i guess they don't showup in the local preview

**Comment by erikarasnick** [comment]
Awesome, I was hoping that would be the case.

**Pull request merged**
