### PR TITLE
add windows example calls

### PR DESCRIPTION
**Pull request by erikarasnick**

### CODE REVIEW

**Comment by andrew-vancil** [comment]
I double checked these on my windows pc and it looks like we're missing the "$" before the "%cd%". However, when I ran the command as is, with the added $, I got the error asking for an absolute filepath. So I tried using the ${pwd} notation and things ran well for me. 

So I think the commands could be:
`docker run --rm -v ${pwd}:/tmp ghcr.io/degauss-org/geocoder:3.0.2 my_address_file.csv` 
When I send stuff to Kris to run, she doesn't usually get any trouble with this format.

I've gotten so used to my macbook that I can't even remember what works and what doesn't on windows :)

**Comment by cole-brokamp** [comment]
I think this depends on which shell program for Windows they are using.  Is this different from what we have here? https://degauss.org/troubleshooting.html#PWD

**Comment by andrew-vancil** [comment]
Oh yeah, that could be it.  I was using PowerShell earlier. I just tried in the regular command prompt and the ${pwd} gave me an error but your original format ran properly in the command prompt. Maybe either a line for both or steer the users to one program or the other? If they have it, I personally prefer PowerShell

**Comment by erikarasnick** [comment]
Yeah, I typically try to leave this out of guides since it is dependent on terminal vs. cmd vs. powershell, and we note it in troubleshooting, but they specifically asked me to add it and it was quick and easy for me to do so I did it 🤷🏼‍♀️

**Comment by cole-brokamp** [comment]
Yes, let's at least specify which windows application these example are for (CMD versus powershell)

**Comment by erikarasnick** [comment]
do you think this is enough? or should we mention powershell specifically as well?

**Comment by cole-brokamp** [comment]
no -- looks good to me, thanks!

**Pull request merged**
